server:
  port: 7890

spring:
  datasource:
    url: jdbc:mysql://xx.xx.xx.xx:3306/xx?serverTimezone=GMT%2b8:00&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xx
    password: xx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      pool-name: uid
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1765000
      auto-commit: true

uid:
  config:
    time-bits: 28
    worker-bits: 22
    seq-bits: 13
    epoch-str: '2016-05-20'

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*.xml